POST http://localhost:3333/events
Content-Type: application/json


{
  "title":"Show1 beneficiente1",
  "details":"Publico em geral",
  "maximumAttendees": 1
}


###
POST http://localhost:3333/events/f992db0a-776f-4cce-8835-62285e6f3658/attendees
Content-Type: application/json

{
  "name":"Ernesto J. Nipute Jr.",
  "email":"nicutejr@gmaild.com"
}


###
GET http://localhost:3333/events/e72666c5-b2ec-42a6-9419-bb009ef7f79b
Content-Type: application/json

###
GET http://localhost:3333/attendees/3/badge
Content-Type: application/json


###
GET http://localhost:3333/attendees/1/check-in
Content-Type: application/json


###
GET http://localhost:3333/events/f992db0a-776f-4cce-8835-62285e6f3658/attendees?query=j
Content-Type: application/json